# Generated by Django 3.0.7 on 2020-07-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecc',
            name='pi',
            field=models.CharField(max_length=3),
        ),
    ]
