dist: xenial
language: python
python:
    - "2.7"
before_install:
    - pip install awscli==1.15.50
script:
    - if [[ $TRAVIS_BRANCH = "master" ]]; then export DOCKER_REPOSITORY="ebutech"; else export DOCKER_REPOSITORY="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"; fi
    - echo REVISION = \"$TRAVIS_COMMIT\" >> RadioDns-PlugIt/config.py
    - docker build -t $DOCKER_REPOSITORY/platform.open.radio RadioDns-PlugIt/.
    - docker build -t $DOCKER_REPOSITORY/vis.open.radio RadioVisServer/.
    - docker build -t $DOCKER_REPOSITORY/platform-proxy.open.radio LightweightPlugitProxy/.
deploy:
    provider: script
    script: bash scripts/docker_push.sh
    on:
        all_branches: true
        condition: $TRAVIS_BRANCH =~ ^develop|master$
