dist: xenial
language: python
python:
    - "3.7"
before_install:
    - pip install awscli==1.15.50
script:
    - echo REVISION = \"$TRAVIS_COMMIT\" >> RadioDns-PlugIt/config.py
    - docker build -t ebutech/platform.open.radio RadioDns-PlugIt/.
    - docker build -t ebutech/vis.open.radio RadioVisServer/.
    - docker build -t ebutech/platform-proxy.open.radio LightweightPlugitProxy/.
deploy:
    provider: script
    script: bash scripts/docker_push.sh
    on:
        all_branches: true
        condition: $TRAVIS_BRANCH =~ ^develop|master$
