version: '3.7'

services:

  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql

  dns_server:
    build: RadioDns-PlugIt/.
    restart: always
    depends_on:
      - database

  reverse_proxy:
    build: nginx/reverse_proxy/.
    ports:
      - "80:5000"
    depends_on:
      - dns_server

volumes:
  db_data:
