version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3.7.8-management-alpine
    hostname: radiodnsrabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
    - "5672:5672"
    - "15672:15672"

  memcached:
    image: memcached:1.5.12-alpine

  vis_server:
    build: RadioVisServer/.
    command: server.py
    restart: always
    depends_on:
    - rabbitmq
    - memcached
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_DEBUG: ${RABBITMQ_DEBUG}
      RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE}
      MONITORING_HOST: ${MONITORING_HOST}
      MONITORING_PORT: ${MONITORING_PORT}
      MONITORING_USER: ${MONITORING_USER}
      MONITORING_PASSWORD: ${MONITORING_PASSWORD}
      MONITORING_VHOST: ${MONITORING_VHOST}
      MONITORING_DEBUG: ${MONITORING_DEBUG}
      MONITORING_EXCHANGE: ${MONITORING_EXCHANGE}
      MONITORING_QUEUE: ${MONITORING_QUEUE}
      MONITORING_SERVER_ID: ${MONITORING_SERVER_ID}
      STOMP_IP: ${STOMP_IP}
      STOMP_PORT: ${STOMP_PORT}
      RADIODNS_API_URL: ${RADIODNS_API_URL}
      FB_CHANNEL_CACHE: ${FB_CHANNEL_CACHE}
      FB_QUEUE: ${FB_QUEUE}
      FB_FALLBACK_CHECK: ${FB_FALLBACK_CHECK}
      FB_FALLBACK_TIME: ${FB_FALLBACK_TIME}
      FB_IMAGE_LOCATIONS: ${FB_IMAGE_LOCATIONS}
      FB_LOGS_MAX_AGE: ${FB_LOGS_MAX_AGE}
      FB_LOGS_CLEANUP: ${FB_LOGS_CLEANUP}
      STATS_GAUGE_APPNAME: ${STATS_GAUGE_APPNAME}
      STATS_GAUGE_NB_CLIENTS: ${STATS_GAUGE_NB_CLIENTS}
      STATS_COUNTER_NBMESSAGE_SENT: ${STATS_COUNTER_NBMESSAGE_SENT}
      STATS_COUNTER_NBMESSAGE_RECV: ${STATS_COUNTER_NBMESSAGE_RECV}
      MEMCACHED_HOST: ${MEMCACHED_HOST}
    ports:
    - "61613:61613"

  fallback:
    build: RadioVisServer/.
    command: fallback.py
    restart: always
    depends_on:
    - rabbitmq
    - vis_server
    - memcached
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_DEBUG: ${RABBITMQ_DEBUG}
      RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE}
      MONITORING_HOST: ${MONITORING_HOST}
      MONITORING_PORT: ${MONITORING_PORT}
      MONITORING_USER: ${MONITORING_USER}
      MONITORING_PASSWORD: ${MONITORING_PASSWORD}
      MONITORING_VHOST: ${MONITORING_VHOST}
      MONITORING_DEBUG: ${MONITORING_DEBUG}
      MONITORING_EXCHANGE: ${MONITORING_EXCHANGE}
      MONITORING_QUEUE: ${MONITORING_QUEUE}
      MONITORING_SERVER_ID: ${MONITORING_SERVER_ID}
      STOMP_IP: ${STOMP_IP}
      STOMP_PORT: ${STOMP_PORT}
      RADIODNS_API_URL: ${RADIODNS_API_URL}
      FB_CHANNEL_CACHE: ${FB_CHANNEL_CACHE}
      FB_QUEUE: ${FB_QUEUE}
      FB_FALLBACK_CHECK: ${FB_FALLBACK_CHECK}
      FB_FALLBACK_TIME: ${FB_FALLBACK_TIME}
      FB_IMAGE_LOCATIONS: ${FB_IMAGE_LOCATIONS}
      FB_LOGS_MAX_AGE: ${FB_LOGS_MAX_AGE}
      FB_LOGS_CLEANUP: ${FB_LOGS_CLEANUP}
      STATS_GAUGE_APPNAME: ${STATS_GAUGE_APPNAME}
      STATS_GAUGE_NB_CLIENTS: ${STATS_GAUGE_NB_CLIENTS}
      STATS_COUNTER_NBMESSAGE_SENT: ${STATS_COUNTER_NBMESSAGE_SENT}
      STATS_COUNTER_NBMESSAGE_RECV: ${STATS_COUNTER_NBMESSAGE_RECV}
      MEMCACHED_HOST: ${MEMCACHED_HOST}
