version: '3.7'

services:

    # ========================== ROUTING ==========================
    reverse_proxy:
        build: Nginx-standalone/.
        restart: always
        environment:
            PLUGIT_PROXY_HOSTNAME: manager.${MAIN_DOMAIN}
            VIS_INTERNAL_HOST: ${VIS_INTERNAL_HOST}
            VIS_ADMIN_HOSTNAME: visadmin.${MAIN_DOMAIN}
            VIS_WEB_SOCKET_ENDPOINT_HOST: ws.vis.${MAIN_DOMAIN}
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - dns_server
            - lpp

    # ========================== LIGHTWEIGHT PLUGIT PROXY ==========================
    lpp_database:
        image: postgres:11-alpine
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

    lpp:
        build: LightweightPlugitProxy/.
        restart: always
        depends_on:
            - lpp_database
        environment:
            DEBUG: ${DEBUG}
            LPP_PORT: ${LPP_PORT}
            PLUGIT_APP_URL: ${PLUGIT_APP_URL}
            SECRET_KEY: ${SECRET_KEY}
            ALLOWED_HOSTS: ${ALLOWED_HOSTS}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USER: ${DATABASE_USER}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_HOST: ${DATABASE_HOST}
            DATABASE_PORT: ${DATABASE_PORT}
            PLUGIT_REMOTE_SERVER_SECRET: ${API_SECRET}
            SU_NAME: ${SU_NAME}
            SU_EMAIL: ${SU_EMAIL}
            SU_PASSWORD: ${SU_PASSWORD}
            DATABASE_CONNECTION_MERCY_TIME: ${DATABASE_CONNECTION_MERCY_TIME}

    # ========================== RADIODNS SERVER ==========================
    database:
        image: mysql:8.0
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    dns_server:
        build: RadioDns-PlugIt/.
        restart: always
        depends_on:
            - database
        environment:
            RADIO_DNS_PORT: ${RADIO_DNS_PORT}
            API_URL: ${API_URL}
            LOGO_INTERNAL_URL:
            LOGO_PUBLIC_URL:
            SQLALCHEMY_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@database:3306/radiodns
            APfI_SECRET: ${API_SECRET}
            AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
            AWS_SECRET_KEY: ${AWS_SECRET_KEY}
            DOMAIN: ${MAIN_DOMAIN}
            XSISERVING_ENABLED: ${XSISERVING_ENABLED}
            XSISERVING_DOMAIN: ${MAIN_DOMAIN}
            RADIOVIS_PORT: ${RADIOVIS_PORT}
            RADIOEPG_PORT: ${RADIOEPG_PORT}
            RADIOTAG_PORT: ${RADIOTAG_PORT}
            RADIOSPI_PORT: ${RADIOSPI_PORT}
            RADIOTAG_ENABLED: ${RADIOTAG_ENABLED}
            RADIOVIS_DNS: vis.${MAIN_DOMAIN}
            RADIOEPG_DNS: epg.${MAIN_DOMAIN}
            RADIOTAG_DNS: tag.${MAIN_DOMAIN}
            RADIOSPI_DNS: spi.${MAIN_DOMAIN}
            DEBUG: ${DEBUG}
            STANDALONE: ${STANDALONE}
            PI_BASE_URL: /${API_SECRET}/
            PI_ALLOWED_NETWORKS: ${PI_ALLOWED_NETWORKS}
            FLASK_LOG_PATH: /opt/app/flask.log
            FLASK_LOG_SIZE: 10485764
            SENTRY_DSN:
            PI_API_VERSION: ${PI_API_VERSION}
            PI_API_NAME: ${PI_API_NAME}
            XML_CACHE_TIMEOUT: ${XML_CACHE_TIMEOUT}
            IMG_CACHE_TIMEOUT: ${IMG_CACHE_TIMEOUT}
            DATABASE_CONNECTION_MERCY_TIME: ${DATABASE_CONNECTION_MERCY_TIME}
            VIS_WEB_SOCKET_ENDPOINT_HOST: ws.vis.${MAIN_DOMAIN}

    # ========================== VIS SERVERS ==========================
    rabbitmq:
        image: rabbitmq:3.7.8-management-alpine
        hostname: radiodnsrabbitmq
        restart: always
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

    memcached:
        image: memcached:1.5.12-alpine

    vis_server:
        build: RadioVisServer/.
        command: server.py
        restart: always
        depends_on:
            - rabbitmq
            - memcached
        environment:
            MONITORING_ENABLED: ${MONITORING_ENABLED}
            RABBITMQ_HOST: ${RABBITMQ_HOST}
            RABBITMQ_PORT: ${RABBITMQ_PORT}
            RABBITMQ_USER: ${RABBITMQ_USER}
            RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
            RABBITMQ_VHOST: ${RABBITMQ_VHOST}
            RABBITMQ_DEBUG: ${RABBITMQ_DEBUG}
            RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE}
            MONITORING_HOST: ${MONITORING_HOST}
            MONITORING_PORT: ${MONITORING_PORT}
            MONITORING_USER: ${RABBITMQ_USER}
            MONITORING_PASSWORD: ${RABBITMQ_PASSWORD}
            MONITORING_VHOST: ${MONITORING_VHOST}
            MONITORING_DEBUG: ${MONITORING_DEBUG}
            MONITORING_EXCHANGE: ${MONITORING_EXCHANGE}
            MONITORING_QUEUE: ${MONITORING_QUEUE}
            MONITORING_SERVER_ID: ${MONITORING_SERVER_ID}
            STOMP_IP: ${STOMP_IP}
            STOMP_PORT: ${STOMP_PORT}
            RADIODNS_API_URL: http://dns_server:5000/${API_SECRET}/action/radiovis/api/${API_SECRET}/
            FB_CHANNEL_CACHE: ${FB_CHANNEL_CACHE}
            FB_QUEUE: ${FB_QUEUE}
            FB_FALLBACK_CHECK: ${FB_FALLBACK_CHECK}
            FB_FALLBACK_TIME: ${FB_FALLBACK_TIME}
            FB_IMAGE_LOCATIONS: ${FB_IMAGE_LOCATIONS}
            FB_LOGS_MAX_AGE: ${FB_LOGS_MAX_AGE}
            FB_LOGS_CLEANUP: ${FB_LOGS_CLEANUP}
            STATS_GAUGE_APPNAME: radiovis.app
            STATS_GAUGE_NB_CLIENTS: nb_tcp_cox
            STATS_COUNTER_NBMESSAGE_SENT: radiovis.app.msg_sent
            STATS_COUNTER_NBMESSAGE_RECV: radiovis.app.msg_recv
            MEMCACHED_HOST: ${MEMCACHED_HOST}
        ports:
            - "61613:61613"

    fallback:
        build: RadioVisServer/.
        command: fallback.py
        restart: always
        depends_on:
            - rabbitmq
            - vis_server
            - memcached
        environment:
            MONITORING_ENABLED: ${MONITORING_ENABLED}
            RABBITMQ_HOST: ${RABBITMQ_HOST}
            RABBITMQ_PORT: ${RABBITMQ_PORT}
            RABBITMQ_USER: ${RABBITMQ_USER}
            RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
            RABBITMQ_VHOST: ${RABBITMQ_VHOST}
            RABBITMQ_DEBUG: ${RABBITMQ_DEBUG}
            RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE}
            MONITORING_HOST: ${MONITORING_HOST}
            MONITORING_PORT: ${MONITORING_PORT}
            MONITORING_USER: ${RABBITMQ_USER}
            MONITORING_PASSWORD: ${RABBITMQ_PASSWORD}
            MONITORING_VHOST: ${MONITORING_VHOST}
            MONITORING_DEBUG: ${MONITORING_DEBUG}
            MONITORING_EXCHANGE: ${MONITORING_EXCHANGE}
            MONITORING_QUEUE: ${MONITORING_QUEUE}
            MONITORING_SERVER_ID: ${MONITORING_SERVER_ID}
            STOMP_IP: ${STOMP_IP}
            STOMP_PORT: ${STOMP_PORT}
            RADIODNS_API_URL: http://dns_server:5000/${API_SECRET}/action/radiovis/api/${API_SECRET}/
            FB_CHANNEL_CACHE: ${FB_CHANNEL_CACHE}
            FB_QUEUE: ${FB_QUEUE}
            FB_FALLBACK_CHECK: ${FB_FALLBACK_CHECK}
            FB_FALLBACK_TIME: ${FB_FALLBACK_TIME}
            FB_IMAGE_LOCATIONS: ${FB_IMAGE_LOCATIONS}
            FB_LOGS_MAX_AGE: ${FB_LOGS_MAX_AGE}
            FB_LOGS_CLEANUP: ${FB_LOGS_CLEANUP}
            STATS_GAUGE_APPNAME: radiovis.app
            STATS_GAUGE_NB_CLIENTS: nb_tcp_cox
            STATS_COUNTER_NBMESSAGE_SENT: radiovis.app.msg_sent
            STATS_COUNTER_NBMESSAGE_RECV: radiovis.app.msg_recv
            MEMCACHED_HOST: ${MEMCACHED_HOST}
volumes:
    db_data:
    pgdata:

