version: '3.7'

services:

  dns_server:
    image: ${DOCKER_REPOSITORY}/platform.open.radio
    restart: always
    environment:
      RADIO_DNS_PORT: ${RADIO_DNS_PORT}
      API_URL: ${API_URL}
      SQLALCHEMY_URL: ${SQLALCHEMY_URL}
      API_SECRET: ${API_SECRET}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      DOMAIN: ${DOMAIN}
      XSISERVING_ENABLED: ${XSISERVING_ENABLED}
      XSISERVING_DOMAIN: ${XSISERVING_DOMAIN}
      RADIOVIS_PORT: ${RADIOVIS_PORT}
      RADIOEPG_PORT: ${RADIOEPG_PORT}
      RADIOTAG_PORT: ${RADIOTAG_PORT}
      RADIOSPI_PORT: ${RADIOSPI_PORT}
      RADIOTAG_ENABLED: ${RADIOTAG_ENABLED}
      RADIOVIS_DNS: ${RADIOVIS_DNS}
      RADIOEPG_DNS: ${RADIOEPG_DNS}
      RADIOTAG_DNS: ${RADIOTAG_DNS}
      RADIOSPI_DNS: ${RADIOSPI_DNS}
      DEBUG: ${DEBUG}
      STANDALONE: ${STANDALONE}
      PI_BASE_URL: ${PI_BASE_URL}
      PI_ALLOWED_NETWORKS: ${PI_ALLOWED_NETWORKS}
      FLASK_LOG_PATH: /opt/app/flask.log
      FLASK_LOG_SIZE: 10485764
      SENTRY_DSN: ${SENTRY_DSN}
      PI_API_VERSION: ${PI_API_VERSION}
      PI_API_NAME: ${PI_API_NAME}
      XML_CACHE_TIMEOUT: ${XML_CACHE_TIMEOUT}
      IMG_CACHE_TIMEOUT: ${IMG_CACHE_TIMEOUT}
      DATABASE_CONNECTION_MERCY_TIME: ${DATABASE_CONNECTION_MERCY_TIME}
      VIS_WEB_SOCKET_ENDPOINT_HOST: ${VIS_WEB_SOCKET_ENDPOINT_HOST}
      USES_CDN: ${USES_CDN}
      SPI_BUCKET_NAME: ${SPI_BUCKET_NAME}
      SPI_GENERATION_INTERVAL: ${SPI_GENERATION_INTERVAL}
      SPI_CLOUDFRONT_DOMAIN: ${SPI_CLOUDFRONT_DOMAIN}

  reverse_proxy:
    build:
      context: Nginx/.
      dockerfile: Dockerfile.prod
    restart: always
    environment:
      VIS_INTERNAL_HOST: ${VIS_INTERNAL_HOST}
      VIS_ADMIN_HOSTNAME: ${VIS_ADMIN_HOSTNAME}
      VIS_WEB_SOCKET_ENDPOINT_HOST: ${VIS_WEB_SOCKET_ENDPOINT_HOST}
    ports:
    - "80:80"
    - "443:443"
    depends_on:
    - dns_server
