version: '3'

services:
  radiodns:
    env_file:
      - .env
    build:
        ./radiodns
    volumes:
      - static_volume:/opt/app/common/static
      - media_volume:/opt/app/common/media
    expose:
      - 8000
    depends_on:
      - radiodns_database
  radiodns_database:
    image: postgres:12.0-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: lpp
      POSTGRES_PASSWORD: 1234
  nginx:
    build:
      context: ./Nginx
      dockerfile: Dockerfile.dev
    volumes:
      - static_volume:/opt/app/common/static
      - media_volume:/opt/app/common/media
    ports:
      - 80:80
    depends_on:
      - radiodns

volumes:
  pgdata:
  static_volume:
  media_volume:
