version: '3.7'

services:

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: plugitdns
      MYSQL_ROOT_PASSWORD: 1234

  plugit_proxy:
    build: standalone_proxy/.
    environment:
      PROXY_HOST: 0.0.0.0:4000
      PLUGIT_SERVER: http://dns_server:5000
      DEBUG: "True"
    ports:
      - "4000:4000"

  mock_api:
    build: MockApi/.
    ports:
      - "8000:8000"
    environment:
      DEBUG: "False"

  dns_server:
    build: RadioDns-PlugIt/.
    restart: always
    depends_on:
      - plugit_proxy
      - database
      - mock_api
    environment:
      SQLALCHEMY_URL: mysql://root:1234@database:3306/plugitdns
      PI_BASE_URL: /
      LOGO_INTERNAL_URL: http://mock_api:8000/uploads
      LOGO_PUBLIC_URL: http://127.0.0.1:8000/uploads
      API_URL: http://mock_api:8000/
      DEBUG: "False"
    ports:
      - "5000:5000"

volumes:
  db_data:
