# Generated by Django 3.0.6 on 2020-05-26 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type_id", models.CharField(max_length=5)),
                ("pi", models.CharField(max_length=4)),
                ("frequency", models.CharField(max_length=5)),
                ("eid", models.CharField(max_length=4)),
                ("sid", models.CharField(max_length=8)),
                ("scids", models.CharField(max_length=3)),
                ("appty_uatype", models.CharField(max_length=6)),
                ("pa", models.IntegerField()),
                ("stream_url", models.CharField(max_length=255)),
                ("bitrate", models.IntegerField()),
                ("mime_type", models.CharField(max_length=64)),
                ("tx", models.CharField(max_length=5)),
                ("cc", models.CharField(max_length=3)),
                ("mid", models.IntegerField()),
                ("fqdn", models.CharField(max_length=255)),
                ("serviceIdentifier", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="Ecc",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("iso", models.CharField(max_length=2)),
                ("pi", models.CharField(max_length=2)),
                ("ecc", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("filename", models.CharField(max_length=255)),
                ("radiotext", models.CharField(max_length=255)),
                ("radiolink", models.CharField(max_length=255)),
                ("image_url_prefix", models.CharField(max_length=255)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="channels.Channel",
                    ),
                ),
            ],
        ),
    ]
