# Generated by Django 3.0.7 on 2020-06-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type_id", models.CharField(max_length=5)),
                ("pi", models.CharField(blank=True, max_length=4, null=True)),
                ("frequency", models.CharField(blank=True, max_length=5, null=True)),
                ("eid", models.CharField(blank=True, max_length=4, null=True)),
                ("sid", models.CharField(blank=True, max_length=8, null=True)),
                ("scids", models.CharField(blank=True, max_length=3, null=True)),
                ("appty_uatype", models.CharField(blank=True, max_length=6, null=True)),
                ("pa", models.IntegerField(blank=True, null=True)),
                ("stream_url", models.CharField(blank=True, max_length=255, null=True)),
                ("bitrate", models.IntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=64, null=True)),
                ("tx", models.CharField(blank=True, max_length=5, null=True)),
                ("mid", models.IntegerField(blank=True, null=True)),
                ("fqdn", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "serviceIdentifier",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("file", models.ImageField(blank=True, null=True, upload_to="")),
                ("radiotext", models.CharField(max_length=255)),
                ("radiolink", models.URLField()),
            ],
        ),
    ]
