# Generated by Django 3.0.7 on 2020-06-10 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stations", "0001_initial"),
        ("channels", "0001_initial"),
        ("localization", "0001_initial"),
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="manager.Organization"
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="default_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="channels.Image",
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="ecc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="localization.Ecc",
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stations.Station"
            ),
        ),
    ]
