# Generated by Django 3.0.6 on 2020-05-26 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0001_initial"),
        ("stations", "0001_initial"),
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="manager.Organization"
            ),
        ),
        migrations.AddField(
            model_name="ecc",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="channels.Channel"
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stations.Station"
            ),
        ),
    ]
