# Generated by Django 3.0.7 on 2020-12-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_auto_20200616_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='radiolink',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='radiotext',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
