# Generated by Django 3.0.7 on 2020-12-08 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20200617_2005'),
        ('channels', '0002_auto_20200616_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stations.Station'),
        ),
    ]
