"""
Django settings for radiodns project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import environ

# Load operating system environment variables and then prepare to use them
env = environ.Env()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
SETTINGS_DIR = environ.Path(__file__) - 1
BASE_DIR = SETTINGS_DIR - 2  # brave30 directory


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "%eea1za680a5x$ah=ts7u+!96=m#%%h1(b4s$w!v_%q1%!o^h*"

# SECURITY WARNING: don"t run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", False)

ALLOWED_HOSTS = []

AUTH_USER_MODEL = "radiodns_auth.User"

APPEND_SLASH = True

# Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

LOCAL_APPS = [
    "common",
    "apps.radiodns_auth",
    "apps.channels",
    "apps.clients",
    "apps.stations",
    "apps.system",
    "apps.manager",
    "apps.radioepg",
    "apps.radiovis",
    "apps.localization",
]

INSTALLED_APPS = DJANGO_APPS + LOCAL_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "apps.radiodns_auth.middleware.LoginRequiredMiddleware",
    "apps.manager.middleware.SetupRequiredMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(BASE_DIR.path("common/templates"))],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

LOGIN_URL = "login/"

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/
LANGUAGE_CODE = "en-us"


TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

SETUP_EXEMPT_URLS = ["setup_error/", "admin/"]

DOMAIN = os.environ.get("DOMAIN", "127.0.0.1")

# Default Service URLs for RadioDNS Services
RADIOVIS_DNS = os.environ.get("RADIOVIS_DNS", "127.0.0.1")
RADIOEPG_DNS = os.environ.get("RADIOEPG_DNS", "127.0.0.1")
RADIOTAG_DNS = os.environ.get("RADIOTAG_DNS", "127.0.0.1")
RADIOSPI_DNS = os.environ.get("RADIOSPI_DNS", "127.0.0.1")

RADIOVIS_PORT = os.environ.get("RADIOVIS_PORT", "61613")
RADIOEPG_PORT = os.environ.get("RADIOEPG_PORT", "5000")
RADIOTAG_PORT = os.environ.get("RADIOTAG_PORT", "5000")
RADIOSPI_PORT = os.environ.get("RADIOSPI_PORT", "5000")

RADIOVIS_SERVICE_DEFAULT = RADIOVIS_DNS + ":" + RADIOVIS_PORT
RADIOEPG_SERVICE_DEFAULT = RADIOEPG_DNS + ":" + RADIOEPG_PORT
RADIOTAG_SERVICE_DEFAULT = RADIOTAG_DNS + ":" + RADIOTAG_PORT
RADIOSPI_SERVICE_DEFAULT = RADIOSPI_DNS + ":" + RADIOSPI_PORT
RADIOTAG_ENABLED = "True" == os.environ.get("RADIOTAG_ENABLED", "False")
