COLORS = [
    ("#e41a1c", "Red"),
    ("#377eb8", "Blue"),
    ("#4daf4a", "Green"),
    ("#984ea3", "Magenta"),
    ("#ff7f00", "Orange"),
    ("#ffff33", "Yellow"),
    ("#a65628", "Brown"),
    ("#f781bf", "Pink"),
    ("#999999", "Gray"),
]

LANGUAGES = [
    ("af", "Afrikaans"),
    ("ak", "Akan"),
    ("an", "aragonés"),
    ("ar", "عربي"),
    ("as", "অসমীয়া"),
    ("ast", "Asturianu"),
    ("az", "Azərbaycanca"),
    ("be", "Беларуская"),
    ("bg", "Български"),
    ("br", "Brezhoneg"),
    ("ca", "Català"),
    ("cs", "Čeština"),
    ("csb", "Kaszëbsczi"),
    ("cy", "Cymraeg"),
    ("da", "Dansk"),
    ("de", "Deutsch"),
    ("dsb", "Dolnoserbšćina"),
    ("el", "Ελληνικά"),
    ("en-GB", "English(British)"),
    ("en-US", "English(US)"),
    ("eo", "Esperanto"),
    ("es-AR", "Español(de Argentina)"),
    ("es-CL", "Español(de Chile)"),
    ("es-ES", "Español(de España)"),
    ("es-MX", "Español(de México)"),
    ("et", "Eesti keel"),
    ("eu", "Euskara"),
    ("fa", "فارسی"),
    ("ff", "Pulaar - Fulfulde"),
    ("fi", "suomi"),
    ("fr", "Français"),
    ("fy-NL", "Frysk"),
    ("ga-IE", "Gaeilge"),
    ("gd", "Gàidhlig"),
    ("gl", "Galego"),
    ("he", "עברית"),
    ("hi-IN", "हिन्दी(भारत)"),
    ("hr", "Hrvatski"),
    ("hsb", "Hornjoserbsce"),
    ("hu", "magyar"),
    ("hy-AM", "Հայերեն"),
    ("id", "Bahasa Indonesia"),
    ("is", "íslenska"),
    ("it", "Italiano"),
    ("ja", "日本語"),
    ("ka", "ქართული"),
    ("kk", "Қазақ"),
    ("km", "ខ្មែរ"),
    ("ko", "한국어"),
    ("ku", "Kurdî"),
    ("lg", "Luganda"),
    ("lij", "Ligure"),
    ("lt", "lietuvių kalba"),
    ("lv", "Latviešu"),
    ("mk", "Македонски"),
    ("ml", "മലയാളം"),
    ("mr", "मराठी"),
    ("ms", "Melayu"),
    ("my", "မြန်မာဘာသာ"),
    ("nb-NO", "Norsk bokmål"),
    ("nl", "Nederlands"),
    ("nso", "Sepedi"),
    ("oc", "occitan(lengadocian)"),
    ("pa-IN", "ਪੰਜਾਬੀ(ਭਾਰਤ)"),
    ("pl", "Polski"),
    ("pt-BR", "Português(do Brasil)"),
    ("pt-PT", "Português(Europeu)"),
    ("rm", "rumantsch"),
    ("ro", "română"),
    ("ru", "Русский"),
    ("sk", "slovenčina"),
    ("sl", "Slovenščina"),
    ("son", "Soŋay"),
    ("sq", "Shqip"),
    ("sr", "Српски"),
    ("sv-SE", "Svenska"),
    ("ta", "தமிழ்"),
    ("te", "తెలుగు"),
    ("th", "ไทย"),
    ("tr", "Türkçe"),
    ("uk", "Українська"),
    ("ur", "اُردو"),
    ("vi", "Tiếng Việt"),
    ("xh", "isiXhosa"),
    ("zh-CN", "中文(简体)"),
    ("zh-TW", "正體中文(繁體)"),
]

COUNTRIES = [
    ("1", "Albania (AL) [9E0]"),
    ("2", "Algeria (DZ) [2E0]"),
    ("3", "Algeria (DZ) [2E0]"),
    ("4", "Andorra (AD) [3E0]"),
    ("5", "Angola (AO) [6D0]"),
    ("6", "Anguilla (AI) [1A2]"),
    ("7", "Antigua and Barbuda (AG) [2A2]"),
    ("8", "Argentina (AR) [AA2]"),
    ("9", "Armenia (AM) [AE4]"),
    ("10", "Aruba (AW) [3A4]"),
    ("11", "Australia - Australian Capital Territory (AU) [1F0]"),
    ("12", "Australia - New South Wales (AU) [2F0]"),
    ("13", "Australia - Northern Territory (AU) [8F0]"),
    ("14", "Australia - Queensland (AU) [4F0]"),
    ("15", "Australia - South Australia (AU) [5F0]"),
    ("16", "Australia - Tasmania (AU) [7F0]"),
    ("17", "Australia - Victoria (AU) [3F0]"),
    ("18", "Australia - Western Australia (AU) [6F0]"),
    ("19", "Austria (AT) [AE0]"),
    ("20", "Azerbaijan (AZ) [BE3]"),
    ("21", "Azores [Portugal] (PT) [8E4]"),
    ("22", "Bahamas (BS) [FA2]"),
    ("23", "Bahrain (BH) [EF0]"),
    ("24", "Bangladesh (BD) [3F1]"),
    ("25", "Barbados (BB) [5A2]"),
    ("26", "Belarus (BY) [FE3]"),
    ("27", "Belarus (BY) [FE3]"),
    ("28", "Belgium (BE) [6E0]"),
    ("29", "Belize (BZ) [6A2]"),
    ("30", "Benin (BJ) [ED0]"),
    ("31", "Bermuda (BM) [CA2]"),
    ("32", "Bhutan (BT) [2F1]"),
    ("33", "Bolivia (BO) [1A3]"),
    ("34", "Bosnia-Herzegovina (BA) [FE4]"),
    ("35", "Botswana (BW) [BD1]"),
    ("36", "Brazil (BR) [BA2]"),
    ("37", "Brunei Darussalam (BN) [BF1]"),
    ("38", "Bulgaria (BG) [8E1]"),
    ("39", "Burkina Faso (BF) [BD0]"),
    ("40", "Burundi (BI) [9D1]"),
    ("41", "Cambodia (KH) [3F2]"),
    ("42", "Cameroon (CM) [1D0]"),
    ("43", "Canada B (CA) [BA1]"),
    ("44", "Canada C (CA) [CA1]"),
    ("45", "Canada D (CA) [DA1]"),
    ("46", "Canada E (CA) [EA1]"),
    ("47", "Canaries [Spain] (ES) [EE2]"),
    ("48", "Canary Islands [Spain] (ES) [EE0]"),
    ("49", "Cape Verde (CV) [6D1]"),
    ("50", "Cayman Islands (KY) [7A2]"),
    ("51", "Central African Republic (CF) [2D0]"),
    ("52", "Chad (TD) [9D2]"),
    ("53", "Chile (CL) [CA3]"),
    ("54", "China (CN) [CF0]"),
    ("55", "Colombia (CO) [2A3]"),
    ("56", "Comoros (KM) [CD1]"),
    ("57", "Congo (CG) [CD0]"),
    ("58", "Costa Rica (CR) [8A2]"),
    ("59", "Cote d.Ivoire (CI) [CD2]"),
    ("60", "Croatia (HR) [CE3]"),
    ("61", "Cuba (CU) [9A2]"),
    ("62", "Cyprus (CY) [2E1]"),
    ("63", "Czech Republic (CZ) [2E2]"),
    ("64", "Democratic Rep. of Congo (ZR) [BD2]"),
    ("65", "Denmark (DK) [9E1]"),
    ("66", "Djibouti (DJ) [3D0]"),
    ("67", "Dominica (DM) [AA3]"),
    ("68", "Dominican Republic (DO) [BA3]"),
    ("69", "Ecuador (EC) [3A2]"),
    ("70", "Egypt (EG) [FE0]"),
    ("71", "Egypt (EG) [FE0]"),
    ("72", "El Salvador (SV) [CA4]"),
    ("73", "Equatorial Guinea (GQ) [7D0]"),
    ("74", "Estonia (EE) [2E4]"),
    ("75", "Estonia (EE) [2E4]"),
    ("76", "Ethiopia (ET) [ED1]"),
    ("77", "Falkland Islands (FK) [4A2]"),
    ("78", "Faroe Islands [Denmark] (DK) [9E1]"),
    ("79", "Fiji (FJ) [5F1]"),
    ("80", "Finland (FI) [6E1]"),
    ("81", "France (FR) [FE1]"),
    ("82", "Gabon (GA) [8D0]"),
    ("83", "Gambia (GM) [8D1]"),
    ("84", "Georgia (GE) [CE4]"),
    ("85", "Germany 1 (DE) [1E0]"),
    ("86", "Germany D (DE) [DE0]"),
    ("87", "Ghana (GH) [3D1]"),
    ("88", "Gibraltar [United Kingdom] (GI) [AE1]"),
    ("89", "Greece (GR) [1E1]"),
    ("90", "Greenland (GL) [FA1]"),
    ("91", "Grenada (GD) [DA3]"),
    ("92", "Guadeloupe (GP) [EA2]"),
    ("93", "Guatemala (GT) [1A4]"),
    ("94", "Guiana (GF) [5A3]"),
    ("95", "Guinea-Bissau (GW) [AD2]"),
    ("96", "Guyana (GY) [FA3]"),
    ("97", "Haiti (HT) [DA4]"),
    ("98", "Honduras (HN) [2A4]"),
    ("99", "Hong Kong (HK) [FF1]"),
    ("100", "Hungary (HU) [BE0]"),
    ("101", "Iceland (IS) [AE2]"),
    ("102", "India (IN) [5F2]"),
    ("103", "Indonesia (ID) [CF2]"),
    ("104", "Iran (IR) [8F0]"),
    ("105", "Iraq (IQ) [BE1]"),
    ("106", "Iraq (IQ) [BE1]"),
    ("107", "Ireland (IE) [2E3]"),
    ("108", "Israel (IL) [4E0]"),
    ("109", "Italy (IT) [5E0]"),
    ("110", "Jamaica (JM) [3A3]"),
    ("111", "Japan (JP) [9F2]"),
    ("112", "Jordan (JO) [5E1]"),
    ("113", "Kazakhstan (KZ) [DE3]"),
    ("114", "Kenya (KE) [6D2]"),
    ("115", "Kiribati (KI) [1F1]"),
    ("116", "Korea [North] (KP) [DF0]"),
    ("117", "Korea [South] (KR) [EF1]"),
    ("118", "Kuwait (KW) [1F2]"),
    ("119", "Kyrgyzstan (KG) [3E4]"),
    ("120", "Laos (LA) [1F3]"),
    ("121", "Latvia (LV) [9E3]"),
    ("122", "Latvia (LV) [9E3]"),
    ("123", "Lebanon (LB) [AE3]"),
    ("124", "Lesotho (LS) [6D3]"),
    ("125", "Liberia (LR) [2D1]"),
    ("126", "Libya (LY) [DE1]"),
    ("127", "Libya (LY) [DE1]"),
    ("128", "Liechtenstein (LI) [9E2]"),
    ("130", "Lithuania (LT) [CE2]"),
    ("129", "Lithuania (LT) [CE2]"),
    ("131", "Luxembourg (LU) [7E1]"),
    ("132", "Macau (MO) [6F2]"),
    ("133", "Macedonia (MK) [4E3]"),
    ("134", "Madagascar (MG) [4D0]"),
    ("135", "Madeira [Portugal] (PT) [8E4]"),
    ("136", "Malawi (MW) [FD0]"),
    ("137", "Malaysia (MY) [FF0]"),
    ("138", "Maldives (MV) [BF2]"),
    ("139", "Mali (ML) [5D0]"),
    ("140", "Malta (MT) [CE0]"),
    ("141", "Martinique (MQ) [4A3]"),
    ("142", "Mauritania (MR) [4D1]"),
    ("143", "Mauritius (MU) [AD3]"),
    ("144", "Mexico B (MX) [BA5]"),
    ("145", "Mexico D (MX) [DA5]"),
    ("146", "Mexico E (MX) [EA5]"),
    ("147", "Mexico F (MX) [FA5]"),
    ("148", "Micronesia (FM) [EF3]"),
    ("149", "Moldova (MD) [1E4]"),
    ("150", "Moldova (MD) [1E4]"),
    ("151", "Monaco (MC) [BE2]"),
    ("152", "Mongolia (MN) [FF3]"),
    ("153", "Montserrat (MS) [5A4]"),
    ("154", "Morocco (MA) [1E2]"),
    ("155", "Morocco (MA) [1E2]"),
    ("156", "Mozambique (MZ) [3D2]"),
    ("157", "Myanmar [Burma] (MM) [BF0]"),
    ("158", "Namibia (NA) [1D1]"),
    ("159", "Nauru (NR) [7F1]"),
    ("160", "Nepal (NP) [EF2]"),
    ("161", "Netherlands (NL) [8E3]"),
    ("162", "Netherlands Antilles (AN) [DA2]"),
    ("163", "New Zealand (NZ) [9F1]"),
    ("164", "Nicaragua (NI) [7A3]"),
    ("165", "Niger (NE) [8D2]"),
    ("166", "Nigeria (NG) [FD1]"),
    ("167", "Norway (NO) [FE2]"),
    ("168", "Oman (OM) [6F1]"),
    ("169", "Pakistan (PK) [4F1]"),
    ("170", "Palestine (PS) [8E0]"),
    ("171", "Panama (A) [9A3]"),
    ("172", "Papua New Guinea (PG) [9F3]"),
    ("173", "Paraguay (PY) [6A3]"),
    ("174", "Peru (PE) [7A4]"),
    ("175", "Philippines (PH) [8F2]"),
    ("176", "Poland (PL) [3E2]"),
    ("177", "Portugal (PT) [8E4]"),
    ("191", "Qatar (QA) [2F2]"),
    ("192", "Republic of Guinea (GN) [9D0]"),
    ("193", "Romania (RO) [EE1]"),
    ("194", "Russian Federation (RU) [7E0]"),
    ("195", "Russian Federation (RU) [7E0]"),
    ("196", "Rwanda (RW) [5D3]"),
    ("197", "Saint Kitts (KN) [AA4]"),
    ("198", "Saint Lucia (LC) [BA4]"),
    ("199", "Saint Vincent (VC) [CA5]"),
    ("200", "San Marino (SM) [3E1]"),
    ("201", "Sao Tome &amp; Principe (ST) [5D1]"),
    ("202", "Saudi Arabia (SA) [9F0]"),
    ("203", "Senegal (SN) [7D1]"),
    ("204", "Seychelles (SC) [8D3]"),
    ("205", "Sierra Leone (SL) [1D2]"),
    ("206", "Singapore (SG) [AF2]"),
    ("207", "Slovakia (SK) [5E2]"),
    ("208", "Slovenia (SI) [9E4]"),
    ("209", "Solomon Islands (SB) [AF1]"),
    ("210", "Somalia (SO) [7D2]"),
    ("211", "South Africa (ZA) [AD0]"),
    ("212", "Spain (ES) [EE2]"),
    ("213", "Sri Lanka (LK) [CF1]"),
    ("214", "St Pierre and Miquelon (PM) [FA6]"),
    ("215", "Sudan (SD) [CD3]"),
    ("216", "Suriname (SR) [8A4]"),
    ("217", "Swaziland (SZ) [5D2]"),
    ("218", "Sweden (SE) [EE3]"),
    ("219", "Switzerland (CH) [4E1]"),
    ("220", "Syrian Arab Republic (SY) [6E2]"),
    ("221", "Taiwan (TW) [DF1]"),
    ("222", "Tajikistan (TJ) [5E3]"),
    ("223", "Tanzania (TZ) [DD1]"),
    ("224", "Thailand (TH) [2F3]"),
    ("225", "Togo (TG) [DD0]"),
    ("226", "Tonga (TO) [3F3]"),
    ("227", "Trinidad and Tobago (TT) [6A4]"),
    ("228", "Tunisia (TN) [7E2]"),
    ("229", "Tunisia (TN) [7E2]"),
    ("230", "Turkey (TR) [3E3]"),
    ("231", "Turkmenistan (TM) [EE4]"),
    ("232", "Turks and Caicos Islands (TC) [EA3]"),
    ("233", "UAE (AE) [DF2]"),
    ("234", "Uganda (UG) [4D2]"),
    ("235", "Ukraine (UA) [6E4]"),
    ("236", "Ukraine (UA) [6E4]"),
    ("237", "United Kingdom (GB) [CE1]"),
    ("238", "United States of America 1 (US) [1A0]"),
    ("239", "United States of America 2 (US) [2A0]"),
    ("240", "United States of America 3 (US) [3A0]"),
    ("241", "United States of America 4 (US) [4A0]"),
    ("242", "United States of America 5 (US) [5A0]"),
    ("243", "United States of America 6 (US) [6A0]"),
    ("244", "United States of America 7 (US) [7A0]"),
    ("245", "United States of America 8 (US) [8A0]"),
    ("246", "United States of America 9 (US) [9A0]"),
    ("247", "United States of America A (US) [AA0]"),
    ("248", "United States of America B (US) [BA0]"),
    ("249", "United States of America D (US) [DA0]"),
    ("250", "United States of America E (US) [EA0]"),
    ("251", "Uruguay (UY) [9A4]"),
    ("252", "Uzbekistan (UZ) [BE4]"),
    ("253", "Vanuatu (VU) [FF2]"),
    ("254", "Vatican City State (VA) [4E2]"),
    ("255", "Venezuela (VE) [EA4]"),
    ("256", "Vietnam (VN) [7F2]"),
    ("257", "Virgin Islands [British] (VG) [FA5]"),
    ("271", "Western Sahara (EH) [3D3]"),
    ("272", "Western Samoa (WS) [4F2]"),
    ("273", "Yemen (YE) [BF3]"),
    ("274", "Yugoslavia (YU) [DE2]"),
    ("275", "Zambia (ZM) [ED2]"),
    ("276", "Zimbabwe (ZW) [2D2]"),
]

COUNTRIES_N_CODES = [
    ("al", "Albania (AL)"),
    ("dz", "Algeria (DZ)"),
    ("dz", "Algeria (DZ)"),
    ("ad", "Andorra (AD)"),
    ("ao", "Angola (AO)"),
    ("ai", "Anguilla (AI)"),
    ("ag", "Antigua and Barbuda (AG)"),
    ("ar", "Argentina (AR)"),
    ("am", "Armenia (AM)"),
    ("aw", "Aruba (AW)"),
    ("au", "Australia - Australian Capital Territory (AU)"),
    ("au", "Australia - New South Wales (AU)"),
    ("au", "Australia - Northern Territory (AU)"),
    ("au", "Australia - Queensland (AU)"),
    ("au", "Australia - South Australia (AU)"),
    ("au", "Australia - Tasmania (AU)"),
    ("au", "Australia - Victoria (AU)"),
    ("au", "Australia - Western Australia (AU)"),
    ("at", "Austria (AT)"),
    ("az", "Azerbaijan (AZ)"),
    ("pt", "Azores [Portugal] (PT)"),
    ("bs", "Bahamas (BS)"),
    ("bh", "Bahrain (BH)"),
    ("bd", "Bangladesh (BD)"),
    ("bb", "Barbados (BB)"),
    ("by", "Belarus (BY)"),
    ("by", "Belarus (BY)"),
    ("be", "Belgium (BE)"),
    ("bz", "Belize (BZ)"),
    ("bj", "Benin (BJ)"),
    ("bm", "Bermuda (BM)"),
    ("bt", "Bhutan (BT)"),
    ("bo", "Bolivia (BO)"),
    ("ba", "Bosnia-Herzegovina (BA)"),
    ("bw", "Botswana (BW)"),
    ("br", "Brazil (BR)"),
    ("bn", "Brunei Darussalam (BN)"),
    ("bg", "Bulgaria (BG)"),
    ("bf", "Burkina Faso (BF)"),
    ("bi", "Burundi (BI)"),
    ("kh", "Cambodia (KH)"),
    ("cm", "Cameroon (CM)"),
    ("ca", "Canada B (CA)"),
    ("ca", "Canada C (CA)"),
    ("ca", "Canada D (CA)"),
    ("ca", "Canada E (CA)"),
    ("es", "Canaries [Spain] (ES)"),
    ("es", "Canary Islands [Spain] (ES)"),
    ("cv", "Cape Verde (CV)"),
    ("ky", "Cayman Islands (KY)"),
    ("cf", "Central African Republic (CF)"),
    ("td", "Chad (TD)"),
    ("cl", "Chile (CL)"),
    ("cn", "China (CN)"),
    ("co", "Colombia (CO)"),
    ("km", "Comoros (KM)"),
    ("cg", "Congo (CG)"),
    ("cr", "Costa Rica (CR)"),
    ("ci", "Cote d.Ivoire (CI)"),
    ("hr", "Croatia (HR)"),
    ("cu", "Cuba (CU)"),
    ("cy", "Cyprus (CY)"),
    ("cz", "Czech Republic (CZ)"),
    ("zr", "Democratic Rep. of Congo (ZR)"),
    ("dk", "Denmark (DK)"),
    ("dj", "Djibouti (DJ)"),
    ("dm", "Dominica (DM)"),
    ("do", "Dominican Republic (DO)"),
    ("ec", "Ecuador (EC)"),
    ("eg", "Egypt (EG)"),
    ("eg", "Egypt (EG)"),
    ("sv", "El Salvador (SV)"),
    ("gq", "Equatorial Guinea (GQ)"),
    ("ee", "Estonia (EE)"),
    ("ee", "Estonia (EE)"),
    ("et", "Ethiopia (ET)"),
    ("fk", "Falkland Islands (FK)"),
    ("dk", "Faroe Islands [Denmark] (DK)"),
    ("fj", "Fiji (FJ)"),
    ("fi", "Finland (FI)"),
    ("fr", "France (FR)"),
    ("ga", "Gabon (GA)"),
    ("gm", "Gambia (GM)"),
    ("ge", "Georgia (GE)"),
    ("de", "Germany 1 (DE)"),
    ("de", "Germany D (DE)"),
    ("gh", "Ghana (GH)"),
    ("gi", "Gibraltar [United Kingdom] (GI)"),
    ("gr", "Greece (GR)"),
    ("gl", "Greenland (GL)"),
    ("gd", "Grenada (GD)"),
    ("gp", "Guadeloupe (GP)"),
    ("gt", "Guatemala (GT)"),
    ("gf", "Guiana (GF)"),
    ("gw", "Guinea-Bissau (GW)"),
    ("gy", "Guyana (GY)"),
    ("ht", "Haiti (HT)"),
    ("hn", "Honduras (HN)"),
    ("hk", "Hong Kong (HK)"),
    ("hu", "Hungary (HU)"),
    ("is", "Iceland (IS)"),
    ("in", "India (IN)"),
    ("id", "Indonesia (ID)"),
    ("ir", "Iran (IR)"),
    ("iq", "Iraq (IQ)"),
    ("iq", "Iraq (IQ)"),
    ("ie", "Ireland (IE)"),
    ("il", "Israel (IL)"),
    ("it", "Italy (IT)"),
    ("jm", "Jamaica (JM)"),
    ("jp", "Japan (JP)"),
    ("jo", "Jordan (JO)"),
    ("kz", "Kazakhstan (KZ)"),
    ("ke", "Kenya (KE)"),
    ("ki", "Kiribati (KI)"),
    ("kp", "Korea [North] (KP)"),
    ("kr", "Korea [South] (KR)"),
    ("kw", "Kuwait (KW)"),
    ("kg", "Kyrgyzstan (KG)"),
    ("la", "Laos (LA)"),
    ("lv", "Latvia (LV)"),
    ("lv", "Latvia (LV)"),
    ("lb", "Lebanon (LB)"),
    ("ls", "Lesotho (LS)"),
    ("lr", "Liberia (LR)"),
    ("ly", "Libya (LY)"),
    ("ly", "Libya (LY)"),
    ("li", "Liechtenstein (LI)"),
    ("lt", "Lithuania (LT)"),
    ("lt", "Lithuania (LT)"),
    ("lu", "Luxembourg (LU)"),
    ("mo", "Macau (MO)"),
    ("mk", "Macedonia (MK)"),
    ("mg", "Madagascar (MG)"),
    ("pt", "Madeira [Portugal] (PT)"),
    ("mw", "Malawi (MW)"),
    ("my", "Malaysia (MY)"),
    ("mv", "Maldives (MV)"),
    ("ml", "Mali (ML)"),
    ("mt", "Malta (MT)"),
    ("mq", "Martinique (MQ)"),
    ("mr", "Mauritania (MR)"),
    ("mu", "Mauritius (MU)"),
    ("mx", "Mexico B (MX)"),
    ("mx", "Mexico D (MX)"),
    ("mx", "Mexico E (MX)"),
    ("mx", "Mexico F (MX)"),
    ("fm", "Micronesia (FM)"),
    ("md", "Moldova (MD)"),
    ("md", "Moldova (MD)"),
    ("mc", "Monaco (MC)"),
    ("mn", "Mongolia (MN)"),
    ("ms", "Montserrat (MS)"),
    ("ma", "Morocco (MA)"),
    ("ma", "Morocco (MA)"),
    ("mz", "Mozambique (MZ)"),
    ("mm", "Myanmar [Burma] (MM)"),
    ("na", "Namibia (NA)"),
    ("nr", "Nauru (NR)"),
    ("np", "Nepal (NP)"),
    ("nl", "Netherlands (NL)"),
    ("an", "Netherlands Antilles (AN)"),
    ("nz", "New Zealand (NZ)"),
    ("ni", "Nicaragua (NI)"),
    ("ne", "Niger (NE)"),
    ("ng", "Nigeria (NG)"),
    ("no", "Norway (NO)"),
    ("om", "Oman (OM)"),
    ("pk", "Pakistan (PK)"),
    ("ps", "Palestine (PS)"),
    ("a", "Panama (A)"),
    ("pg", "Papua New Guinea (PG)"),
    ("py", "Paraguay (PY)"),
    ("pe", "Peru (PE)"),
    ("ph", "Philippines (PH)"),
    ("pl", "Poland (PL)"),
    ("pt", "Portugal (PT)"),
    ("qa", "Qatar (QA)"),
    ("gn", "Republic of Guinea (GN)"),
    ("ro", "Romania (RO)"),
    ("ru", "Russian Federation (RU)"),
    ("ru", "Russian Federation (RU)"),
    ("rw", "Rwanda (RW)"),
    ("kn", "Saint Kitts (KN)"),
    ("lc", "Saint Lucia (LC)"),
    ("vc", "Saint Vincent (VC)"),
    ("sm", "San Marino (SM)"),
    ("st", "Sao Tome &amp; Principe (ST)"),
    ("sa", "Saudi Arabia (SA)"),
    ("sn", "Senegal (SN)"),
    ("sc", "Seychelles (SC)"),
    ("sl", "Sierra Leone (SL)"),
    ("sg", "Singapore (SG)"),
    ("sk", "Slovakia (SK)"),
    ("si", "Slovenia (SI)"),
    ("sb", "Solomon Islands (SB)"),
    ("so", "Somalia (SO)"),
    ("za", "South Africa (ZA)"),
    ("es", "Spain (ES)"),
    ("lk", "Sri Lanka (LK)"),
    ("pm", "St Pierre and Miquelon (PM)"),
    ("sd", "Sudan (SD)"),
    ("sr", "Suriname (SR)"),
    ("sz", "Swaziland (SZ)"),
    ("se", "Sweden (SE)"),
    ("ch", "Switzerland (CH)"),
    ("sy", "Syrian Arab Republic (SY)"),
    ("tw", "Taiwan (TW)"),
    ("tj", "Tajikistan (TJ)"),
    ("tz", "Tanzania (TZ)"),
    ("th", "Thailand (TH)"),
    ("tg", "Togo (TG)"),
    ("to", "Tonga (TO)"),
    ("tt", "Trinidad and Tobago (TT)"),
    ("tn", "Tunisia (TN)"),
    ("tn", "Tunisia (TN)"),
    ("tr", "Turkey (TR)"),
    ("tm", "Turkmenistan (TM)"),
    ("tc", "Turks and Caicos Islands (TC)"),
    ("ae", "UAE (AE)"),
    ("ug", "Uganda (UG)"),
    ("ua", "Ukraine (UA)"),
    ("ua", "Ukraine (UA)"),
    ("gb", "United Kingdom (GB)"),
    ("us", "United States of America 1 (US)"),
    ("us", "United States of America 2 (US)"),
    ("us", "United States of America 3 (US)"),
    ("us", "United States of America 4 (US)"),
    ("us", "United States of America 5 (US)"),
    ("us", "United States of America 6 (US)"),
    ("us", "United States of America 7 (US)"),
    ("us", "United States of America 8 (US)"),
    ("us", "United States of America 9 (US)"),
    ("us", "United States of America A (US)"),
    ("us", "United States of America B (US)"),
    ("us", "United States of America D (US)"),
    ("us", "United States of America E (US)"),
    ("uy", "Uruguay (UY)"),
    ("uz", "Uzbekistan (UZ)"),
    ("vu", "Vanuatu (VU)"),
    ("va", "Vatican City State (VA)"),
    ("ve", "Venezuela (VE)"),
    ("vn", "Vietnam (VN)"),
    ("vg", "Virgin Islands [British] (VG)"),
    ("eh", "Western Sahara (EH)"),
    ("ws", "Western Samoa (WS)"),
    ("ye", "Yemen (YE)"),
    ("yu", "Yugoslavia (YU)"),
    ("zm", "Zambia (ZM)"),
    ("zw", "Zimbabwe (ZW)"),
]
