"""Added parameters to channels

Revision ID: 1461ccb47bf0
Revises: 37826dbd06d5
Create Date: 2013-08-05 17:40:16.244000

"""

# revision identifiers, used by Alembic.
revision = '1461ccb47bf0'
down_revision = '37826dbd06d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('appty_uatype', sa.String(length=6), nullable=True))
    op.add_column('channel', sa.Column('cc', sa.String(length=3), nullable=True))
    op.add_column('channel', sa.Column('ecc_id', sa.Integer(), nullable=True))
    op.add_column('channel', sa.Column('eid', sa.String(length=4), nullable=True))
    op.add_column('channel', sa.Column('fqdn', sa.String(length=255), nullable=True))
    op.add_column('channel', sa.Column('frequency', sa.String(length=5), nullable=True))
    op.add_column('channel', sa.Column('pa', sa.Integer(), nullable=True))
    op.add_column('channel', sa.Column('pi', sa.String(length=4), nullable=True))
    op.add_column('channel', sa.Column('scids', sa.String(length=3), nullable=True))
    op.add_column('channel', sa.Column('serviceIdentifier', sa.String(length=16), nullable=True))
    op.add_column('channel', sa.Column('sid', sa.String(length=8), nullable=True))
    op.add_column('channel', sa.Column('tx', sa.String(length=5), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'tx')
    op.drop_column('channel', 'sid')
    op.drop_column('channel', 'serviceIdentifier')
    op.drop_column('channel', 'scids')
    op.drop_column('channel', 'pi')
    op.drop_column('channel', 'pa')
    op.drop_column('channel', 'frequency')
    op.drop_column('channel', 'fqdn')
    op.drop_column('channel', 'eid')
    op.drop_column('channel', 'ecc_id')
    op.drop_column('channel', 'cc')
    op.drop_column('channel', 'appty_uatype')
    ### end Alembic commands ###
