"""Added password

Revision ID: 3530e49c9b85
Revises: 33c72a47d6bb
Create Date: 2013-08-08 14:57:19.603000

"""

# revision identifiers, used by Alembic.
revision = '3530e49c9b85'
down_revision = '33c72a47d6bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('random_password', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('station', 'random_password')
    ### end Alembic commands ###
