# Generated by Django 3.0.6 on 2020-05-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("identifier", models.CharField(max_length=128)),
                ("email", models.CharField(max_length=255)),
            ],
        ),
    ]
