# Generated by Django 3.0.6 on 2020-05-26 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="manager.Organization"
            ),
        ),
    ]
