"""
Create default ECC records
"""

from django.core.management.base import BaseCommand

from apps.localization.models import Ecc

COUNTRIES_N_CODES = [
    ("1", "9E0", "al", "Albania (AL)"),
    ("2", "2E0", "dz", "Algeria (DZ)"),
    ("3", "2E0", "dz", "Algeria (DZ)"),
    ("4", "3E0", "ad", "Andorra (AD)"),
    ("5", "6D0", "ao", "Angola (AO)"),
    ("6", "1A2", "ai", "Anguilla (AI)"),
    ("7", "2A2", "ag", "Antigua and Barbuda (AG)"),
    ("8", "AA2", "ar", "Argentina (AR)"),
    ("9", "AE4", "am", "Armenia (AM)"),
    ("10", "3A4", "aw", "Aruba (AW)"),
    ("11", "1F0", "au", "Australia - Australian Capital Territory (AU)"),
    ("12", "2F0", "au", "Australia - New South Wales (AU)"),
    ("13", "8F0", "au", "Australia - Northern Territory (AU)"),
    ("14", "4F0", "au", "Australia - Queensland (AU)"),
    ("15", "5F0", "au", "Australia - South Australia (AU)"),
    ("16", "7F0", "au", "Australia - Tasmania (AU)"),
    ("17", "3F0", "au", "Australia - Victoria (AU)"),
    ("18", "6F0", "au", "Australia - Western Australia (AU)"),
    ("19", "AE0", "at", "Austria (AT)"),
    ("20", "BE3", "az", "Azerbaijan (AZ)"),
    ("21", "8E4", "pt", "Azores Portugal (PT)"),
    ("22", "FA2", "bs", "Bahamas (BS)"),
    ("23", "EF0", "bh", "Bahrain (BH)"),
    ("24", "3F1", "bd", "Bangladesh (BD)"),
    ("25", "5A2", "bb", "Barbados (BB)"),
    ("26", "FE3", "by", "Belarus (BY)"),
    ("27", "FE3", "by", "Belarus (BY)"),
    ("28", "6E0", "be", "Belgium (BE)"),
    ("29", "6A2", "bz", "Belize (BZ)"),
    ("30", "ED0", "bj", "Benin (BJ)"),
    ("31", "CA2", "bm", "Bermuda (BM)"),
    ("32", "2F1", "bt", "Bhutan (BT)"),
    ("33", "1A3", "bo", "Bolivia (BO)"),
    ("34", "FE4", "ba", "Bosnia-Herzegovina (BA)"),
    ("35", "BD1", "bw", "Botswana (BW)"),
    ("36", "BA2", "br", "Brazil (BR)"),
    ("37", "BF1", "bn", "Brunei Darussalam (BN)"),
    ("38", "8E1", "bg", "Bulgaria (BG)"),
    ("39", "BD0", "bf", "Burkina Faso (BF)"),
    ("40", "9D1", "bi", "Burundi (BI)"),
    ("41", "3F2", "kh", "Cambodia (KH)"),
    ("42", "1D0", "cm", "Cameroon (CM)"),
    ("43", "BA1", "ca", "Canada B (CA)"),
    ("44", "CA1", "ca", "Canada C (CA)"),
    ("45", "DA1", "ca", "Canada D (CA)"),
    ("46", "EA1", "ca", "Canada E (CA)"),
    ("47", "EE2", "es", "Canaries Spain (ES)"),
    ("48", "EE0", "es", "Canary Islands Spain (ES)"),
    ("49", "6D1", "cv", "Cape Verde (CV)"),
    ("50", "7A2", "ky", "Cayman Islands (KY)"),
    ("51", "2D0", "cf", "Central African Republic (CF)"),
    ("52", "9D2", "td", "Chad (TD)"),
    ("53", "CA3", "cl", "Chile (CL)"),
    ("54", "CF0", "cn", "China (CN)"),
    ("55", "2A3", "co", "Colombia (CO)"),
    ("56", "CD1", "km", "Comoros (KM)"),
    ("57", "CD0", "cg", "Congo (CG)"),
    ("58", "8A2", "cr", "Costa Rica (CR)"),
    ("59", "CD2", "ci", "Cote d.Ivoire (CI)"),
    ("60", "CE3", "hr", "Croatia (HR)"),
    ("61", "9A2", "cu", "Cuba (CU)"),
    ("62", "2E1", "cy", "Cyprus (CY)"),
    ("63", "2E2", "cz", "Czech Republic (CZ)"),
    ("64", "BD2", "zr", "Democratic Rep. of Congo (ZR)"),
    ("65", "9E1", "dk", "Denmark (DK)"),
    ("66", "3D0", "dj", "Djibouti (DJ)"),
    ("67", "AA3", "dm", "Dominica (DM)"),
    ("68", "BA3", "do", "Dominican Republic (DO)"),
    ("69", "3A2", "ec", "Ecuador (EC)"),
    ("70", "FE0", "eg", "Egypt (EG)"),
    ("71", "FE0", "eg", "Egypt (EG)"),
    ("72", "CA4", "sv", "El Salvador (SV)"),
    ("73", "7D0", "gq", "Equatorial Guinea (GQ)"),
    ("74", "2E4", "ee", "Estonia (EE)"),
    ("75", "2E4", "ee", "Estonia (EE)"),
    ("76", "ED1", "et", "Ethiopia (ET)"),
    ("77", "4A2", "fk", "Falkland Islands (FK)"),
    ("78", "9E1", "dk", "Faroe Islands Denmark (DK)"),
    ("79", "5F1", "fj", "Fiji (FJ)"),
    ("80", "6E1", "fi", "Finland (FI)"),
    ("81", "FE1", "fr", "France (FR)"),
    ("82", "8D0", "ga", "Gabon (GA)"),
    ("83", "8D1", "gm", "Gambia (GM)"),
    ("84", "CE4", "ge", "Georgia (GE)"),
    ("85", "1E0", "de", "Germany 1 (DE)"),
    ("86", "DE0", "de", "Germany D (DE)"),
    ("87", "3D1", "gh", "Ghana (GH)"),
    ("88", "AE1", "gi", "Gibraltar United Kingdom (GI)"),
    ("89", "1E1", "gr", "Greece (GR)"),
    ("90", "FA1", "gl", "Greenland (GL)"),
    ("91", "DA3", "gd", "Grenada (GD)"),
    ("92", "EA2", "gp", "Guadeloupe (GP)"),
    ("93", "1A4", "gt", "Guatemala (GT)"),
    ("94", "5A3", "gf", "Guiana (GF)"),
    ("95", "AD2", "gw", "Guinea-Bissau (GW)"),
    ("96", "FA3", "gy", "Guyana (GY)"),
    ("97", "DA4", "ht", "Haiti (HT)"),
    ("98", "2A4", "hn", "Honduras (HN)"),
    ("99", "FF1", "hk", "Hong Kong (HK)"),
    ("100", "BE0", "hu", "Hungary (HU)"),
    ("101", "AE2", "is", "Iceland (IS)"),
    ("102", "5F2", "in", "India (IN)"),
    ("103", "CF2", "id", "Indonesia (ID)"),
    ("104", "8F0", "ir", "Iran (IR)"),
    ("105", "BE1", "iq", "Iraq (IQ)"),
    ("106", "BE1", "iq", "Iraq (IQ)"),
    ("107", "2E3", "ie", "Ireland (IE)"),
    ("108", "4E0", "il", "Israel (IL)"),
    ("109", "5E0", "it", "Italy (IT)"),
    ("110", "3A3", "jm", "Jamaica (JM)"),
    ("111", "9F2", "jp", "Japan (JP)"),
    ("112", "5E1", "jo", "Jordan (JO)"),
    ("113", "DE3", "kz", "Kazakhstan (KZ)"),
    ("114", "6D2", "ke", "Kenya (KE)"),
    ("115", "1F1", "ki", "Kiribati (KI)"),
    ("116", "DF0", "kp", "Korea North (KP)"),
    ("117", "EF1", "kr", "Korea South (KR)"),
    ("118", "1F2", "kw", "Kuwait (KW)"),
    ("119", "3E4", "kg", "Kyrgyzstan (KG)"),
    ("120", "1F3", "la", "Laos (LA)"),
    ("121", "9E3", "lv", "Latvia (LV)"),
    ("122", "9E3", "lv", "Latvia (LV)"),
    ("123", "AE3", "lb", "Lebanon (LB)"),
    ("124", "6D3", "ls", "Lesotho (LS)"),
    ("125", "2D1", "lr", "Liberia (LR)"),
    ("126", "DE1", "ly", "Libya (LY)"),
    ("127", "DE1", "ly", "Libya (LY)"),
    ("128", "9E2", "li", "Liechtenstein (LI)"),
    ("130", "CE2", "lt", "Lithuania (LT)"),
    ("129", "CE2", "lt", "Lithuania (LT)"),
    ("131", "7E1", "lu", "Luxembourg (LU)"),
    ("132", "6F2", "mo", "Macau (MO)"),
    ("133", "4E3", "mk", "Macedonia (MK)"),
    ("134", "4D0", "mg", "Madagascar (MG)"),
    ("135", "8E4", "pt", "Madeira Portugal (PT)"),
    ("136", "FD0", "mw", "Malawi (MW)"),
    ("137", "FF0", "my", "Malaysia (MY)"),
    ("138", "BF2", "mv", "Maldives (MV)"),
    ("139", "5D0", "ml", "Mali (ML)"),
    ("140", "CE0", "mt", "Malta (MT)"),
    ("141", "4A3", "mq", "Martinique (MQ)"),
    ("142", "4D1", "mr", "Mauritania (MR)"),
    ("143", "AD3", "mu", "Mauritius (MU)"),
    ("144", "BA5", "mx", "Mexico B (MX)"),
    ("145", "DA5", "mx", "Mexico D (MX)"),
    ("146", "EA5", "mx", "Mexico E (MX)"),
    ("147", "FA5", "mx", "Mexico F (MX)"),
    ("148", "EF3", "fm", "Micronesia (FM)"),
    ("149", "1E4", "md", "Moldova (MD)"),
    ("150", "1E4", "md", "Moldova (MD)"),
    ("151", "BE2", "mc", "Monaco (MC)"),
    ("152", "FF3", "mn", "Mongolia (MN)"),
    ("153", "5A4", "ms", "Montserrat (MS)"),
    ("154", "1E2", "ma", "Morocco (MA)"),
    ("155", "1E2", "ma", "Morocco (MA)"),
    ("156", "3D2", "mz", "Mozambique (MZ)"),
    ("157", "BF0", "mm", "Myanmar Burma (MM)"),
    ("158", "1D1", "na", "Namibia (NA)"),
    ("159", "7F1", "nr", "Nauru (NR)"),
    ("160", "EF2", "np", "Nepal (NP)"),
    ("161", "8E3", "nl", "Netherlands (NL)"),
    ("162", "DA2", "an", "Netherlands Antilles (AN)"),
    ("163", "9F1", "nz", "New Zealand (NZ)"),
    ("164", "7A3", "ni", "Nicaragua (NI)"),
    ("165", "8D2", "ne", "Niger (NE)"),
    ("166", "FD1", "ng", "Nigeria (NG)"),
    ("167", "FE2", "no", "Norway (NO)"),
    ("168", "6F1", "om", "Oman (OM)"),
    ("169", "4F1", "pk", "Pakistan (PK)"),
    ("170", "8E0", "ps", "Palestine (PS)"),
    ("171", "9A3", "a", "Panama (A)"),
    ("172", "9F3", "pg", "Papua New Guinea (PG)"),
    ("173", "6A3", "py", "Paraguay (PY)"),
    ("174", "7A4", "pe", "Peru (PE)"),
    ("175", "8F2", "ph", "Philippines (PH)"),
    ("176", "3E2", "pl", "Poland (PL)"),
    ("177", "8E4", "pt", "Portugal (PT)"),
    ("191", "2F2", "qa", "Qatar (QA)"),
    ("192", "9D0", "gn", "Republic of Guinea (GN)"),
    ("193", "EE1", "ro", "Romania (RO)"),
    ("194", "7E0", "ru", "Russian Federation (RU)"),
    ("195", "7E0", "ru", "Russian Federation (RU)"),
    ("196", "5D3", "rw", "Rwanda (RW)"),
    ("197", "AA4", "kn", "Saint Kitts (KN)"),
    ("198", "BA4", "lc", "Saint Lucia (LC)"),
    ("199", "CA5", "vc", "Saint Vincent (VC)"),
    ("200", "3E1", "sm", "San Marino (SM)"),
    ("201", "5D1", "st", "Sao Tome &amp; Principe (ST)"),
    ("202", "9F0", "sa", "Saudi Arabia (SA)"),
    ("203", "7D1", "sn", "Senegal (SN)"),
    ("204", "8D3", "sc", "Seychelles (SC)"),
    ("205", "1D2", "sl", "Sierra Leone (SL)"),
    ("206", "AF2", "sg", "Singapore (SG)"),
    ("207", "5E2", "sk", "Slovakia (SK)"),
    ("208", "9E4", "si", "Slovenia (SI)"),
    ("209", "AF1", "sb", "Solomon Islands (SB)"),
    ("210", "7D2", "so", "Somalia (SO)"),
    ("211", "AD0", "za", "South Africa (ZA)"),
    ("212", "EE2", "es", "Spain (ES)"),
    ("213", "CF1", "lk", "Sri Lanka (LK)"),
    ("214", "FA6", "pm", "St Pierre and Miquelon (PM)"),
    ("215", "CD3", "sd", "Sudan (SD)"),
    ("216", "8A4", "sr", "Suriname (SR)"),
    ("217", "5D2", "sz", "Swaziland (SZ)"),
    ("218", "EE3", "se", "Sweden (SE)"),
    ("219", "4E1", "ch", "Switzerland (CH)"),
    ("220", "6E2", "sy", "Syrian Arab Republic (SY)"),
    ("221", "DF1", "tw", "Taiwan (TW)"),
    ("222", "5E3", "tj", "Tajikistan (TJ)"),
    ("223", "DD1", "tz", "Tanzania (TZ)"),
    ("224", "2F3", "th", "Thailand (TH)"),
    ("225", "DD0", "tg", "Togo (TG)"),
    ("226", "3F3", "to", "Tonga (TO)"),
    ("227", "6A4", "tt", "Trinidad and Tobago (TT)"),
    ("228", "7E2", "tn", "Tunisia (TN)"),
    ("229", "7E2", "tn", "Tunisia (TN)"),
    ("230", "3E3", "tr", "Turkey (TR)"),
    ("231", "EE4", "tm", "Turkmenistan (TM)"),
    ("232", "EA3", "tc", "Turks and Caicos Islands (TC)"),
    ("233", "DF2", "ae", "UAE (AE)"),
    ("234", "4D2", "ug", "Uganda (UG)"),
    ("235", "6E4", "ua", "Ukraine (UA)"),
    ("236", "6E4", "ua", "Ukraine (UA)"),
    ("237", "CE1", "gb", "United Kingdom (GB)"),
    ("238", "1A0", "us", "United States of America 1 (US)"),
    ("239", "2A0", "us", "United States of America 2 (US)"),
    ("240", "3A0", "us", "United States of America 3 (US)"),
    ("241", "4A0", "us", "United States of America 4 (US)"),
    ("242", "5A0", "us", "United States of America 5 (US)"),
    ("243", "6A0", "us", "United States of America 6 (US)"),
    ("244", "7A0", "us", "United States of America 7 (US)"),
    ("245", "8A0", "us", "United States of America 8 (US)"),
    ("246", "9A0", "us", "United States of America 9 (US)"),
    ("247", "AA0", "us", "United States of America A (US)"),
    ("248", "BA0", "us", "United States of America B (US)"),
    ("249", "DA0", "us", "United States of America D (US)"),
    ("250", "EA0", "us", "United States of America E (US)"),
    ("251", "9A4", "uy", "Uruguay (UY)"),
    ("252", "BE4", "uz", "Uzbekistan (UZ)"),
    ("253", "FF2", "vu", "Vanuatu (VU)"),
    ("254", "4E2", "va", "Vatican City State (VA)"),
    ("255", "EA4", "ve", "Venezuela (VE)"),
    ("256", "7F2", "vn", "Vietnam (VN)"),
    ("257", "FA5", "vg", "Virgin Islands British (VG)"),
    ("271", "3D3", "eh", "Western Sahara (EH)"),
    ("272", "4F2", "ws", "Western Samoa (WS)"),
    ("273", "BF3", "ye", "Yemen (YE)"),
    ("274", "DE2", "yu", "Yugoslavia (YU)"),
    ("275", "ED2", "zm", "Zambia (ZM)"),
    ("276", "2D2", "zw", "Zimbabwe (ZW)"),
]


class Command(BaseCommand):
    help = "Creates default ECC records"

    def handle(self, *args, **options):
        for line in COUNTRIES_N_CODES:
            new_ecc, created = Ecc.objects.get_or_create(
                name=line[3], iso=line[2], ecc=line[1], pi=line[0]
            )
            new_ecc.save()

        print("Created default ECC records")
