# Generated by Django 3.0.6 on 2020-06-05 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiovis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
