# Generated by Django 3.0.7 on 2020-12-10 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_auto_20201209_1415'),
        ('channels', '0003_auto_20201209_1407'),
        ('radioepg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericservicefollowingentry',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='channels.Channel'),
        ),
        migrations.AlterField(
            model_name='genericservicefollowingentry',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stations.Station'),
        ),
    ]
