# Generated by Django 3.0.7 on 2020-12-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioepg', '0002_auto_20201210_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericservicefollowingentry',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
