# Generated by Django 3.0.7 on 2020-06-10 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("localization", "0001_initial"),
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("short_name", models.CharField(max_length=8)),
                ("medium_name", models.CharField(max_length=16)),
                ("long_name", models.CharField(max_length=128)),
                ("short_description", models.CharField(max_length=180)),
                ("url_default", models.URLField(blank=True, null=True)),
                (
                    "postal_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("sms_number", models.CharField(blank=True, max_length=128, null=True)),
                ("sms_body", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sms_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email_address",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "email_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("radiovis_enabled", models.BooleanField(default=False)),
                ("radiovis_service", models.CharField(blank=True, max_length=255)),
                ("radioepg_enabled", models.BooleanField(blank=True, default=False)),
                ("radioepgpi_enabled", models.BooleanField(default=False)),
                ("radioepg_service", models.CharField(blank=True, max_length=255)),
                ("radiotag_enabled", models.BooleanField(default=False)),
                ("radiotag_service", models.CharField(blank=True, max_length=255)),
                ("radiospi_enabled", models.BooleanField(default=False)),
                (
                    "radiospi_service",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ip_allowed", models.CharField(blank=True, max_length=256, null=True)),
                ("genres", models.TextField(blank=True, null=True)),
                (
                    "default_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="manager.LogoImage",
                    ),
                ),
                (
                    "default_language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="localization.Language",
                    ),
                ),
                (
                    "location_country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="localization.Ecc",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manager.Organization",
                    ),
                ),
            ],
        ),
    ]
