# Generated by Django 3.0.7 on 2020-06-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="stationinstance", name="ip_allowed",),
        migrations.RemoveField(model_name="stationinstance", name="radioepg_enabled",),
        migrations.RemoveField(model_name="stationinstance", name="radioepg_service",),
        migrations.RemoveField(
            model_name="stationinstance", name="radioepgpi_enabled",
        ),
        migrations.RemoveField(model_name="stationinstance", name="radiospi_enabled",),
        migrations.RemoveField(model_name="stationinstance", name="radiospi_service",),
        migrations.RemoveField(model_name="stationinstance", name="radiotag_enabled",),
        migrations.RemoveField(model_name="stationinstance", name="radiotag_service",),
        migrations.RemoveField(model_name="stationinstance", name="radiovis_enabled",),
        migrations.RemoveField(model_name="stationinstance", name="radiovis_service",),
        migrations.AddField(
            model_name="station",
            name="ip_allowed",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="radioepg_enabled",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="station",
            name="radioepg_service",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="station",
            name="radioepgpi_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="station",
            name="radiospi_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="station",
            name="radiospi_service",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="radiotag_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="station",
            name="radiotag_service",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="station",
            name="radiovis_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="station",
            name="radiovis_service",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
