# Generated by Django 3.0.7 on 2020-12-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_auto_20201208_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='radioepg_enabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='radioepgpi_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='radiospi_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='radiotag_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='radiovis_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
