"""Added PI enable option

Revision ID: 10249d62fb55
Revises: 5783809706d2
Create Date: 2015-07-15 18:43:49.238335

"""

# revision identifiers, used by Alembic.
revision = '10249d62fb55'
down_revision = '5783809706d2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'channel', 'picture', ['default_picture_id'], ['id'])
    op.create_foreign_key(None, 'channel', 'ecc', ['ecc_id'], ['id'])
    op.create_index(op.f('ix_log_entry_reception_timestamp'), 'log_entry', ['reception_timestamp'], unique=False)
    op.create_index(op.f('ix_log_entry_topic'), 'log_entry', ['topic'], unique=False)
    op.create_foreign_key('fk_default_logo_id', 'service_provider', 'logo_image', ['default_logo_image_id'], ['id'])
    op.create_foreign_key(None, 'show', 'station', ['station_id'], ['id'])
    op.add_column('station', sa.Column('radioepgpi_enabled', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_station_radioepgpi_enabled'), 'station', ['radioepgpi_enabled'], unique=False)
    op.create_foreign_key(None, 'station', 'service_provider', ['service_provider_id'], ['id'])
    op.create_foreign_key('fk_epg_default_logo_id', 'station', 'logo_image', ['default_logo_image_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_epg_default_logo_id', 'station', type_='foreignkey')
    op.drop_constraint(None, 'station', type_='foreignkey')
    op.drop_index(op.f('ix_station_radioepgpi_enabled'), table_name='station')
    op.drop_column('station', 'radioepgpi_enabled')
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_constraint('fk_default_logo_id', 'service_provider', type_='foreignkey')
    op.drop_index(op.f('ix_log_entry_topic'), table_name='log_entry')
    op.drop_index(op.f('ix_log_entry_reception_timestamp'), table_name='log_entry')
    op.drop_constraint(None, 'channel', type_='foreignkey')
    op.drop_constraint(None, 'channel', type_='foreignkey')
    ### end Alembic commands ###
