"""Added bitrate to servicefollowing

Revision ID: 1144b3a7bfc2
Revises: 10249d62fb55
Create Date: 2015-07-16 18:38:51.637683

"""

# revision identifiers, used by Alembic.
revision = '1144b3a7bfc2'
down_revision = '10249d62fb55'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generic_service_following_entry', sa.Column('bitrate', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generic_service_following_entry', 'bitrate')
    ### end Alembic commands ###
