"""Added PictureForEPG 2

Revision ID: 18287b7e1999
Revises: 33741d7ea890
Create Date: 2014-06-03 14:17:19.707093

"""

# revision identifiers, used by Alembic.
revision = '18287b7e1999'
down_revision = '33741d7ea890'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('epg_picture', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'epg_picture')
    ### end Alembic commands ###
