"""Added Pictures

Revision ID: 1e1119ba9a4
Revises: 465e7dae3728
Create Date: 2013-08-06 14:50:37.765000

"""

# revision identifiers, used by Alembic.
revision = '1e1119ba9a4'
down_revision = '465e7dae3728'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orga', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('radiotext', sa.String(length=255), nullable=True),
    sa.Column('radiolink', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picture')
    ### end Alembic commands ###
