"""mine_type -> mime_type ^^

Revision ID: 1e9f6460c977
Revises: 4121a98095b5
Create Date: 2013-08-23 09:42:21.241000

"""

# revision identifiers, used by Alembic.
revision = '1e9f6460c977'
down_revision = '4121a98095b5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generic_service_following_entry', sa.Column('mime_type', sa.String(length=255), nullable=True))
    op.drop_column('generic_service_following_entry', u'mine_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generic_service_following_entry', sa.Column(u'mine_type', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('generic_service_following_entry', 'mime_type')
    ### end Alembic commands ###
