"""Added allowd_ip

Revision ID: 1eb3f00520c
Revises: 3530e49c9b85
Create Date: 2013-08-09 09:07:07.247000

"""

# revision identifiers, used by Alembic.
revision = '1eb3f00520c'
down_revision = '3530e49c9b85'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('ip_allowed', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('station', 'ip_allowed')
    ### end Alembic commands ###
