"""Added short name

Revision ID: 1f5a646334e1
Revises: 1e9f6460c977
Create Date: 2014-05-09 10:17:17.150660

"""

# revision identifiers, used by Alembic.
revision = '1f5a646334e1'
down_revision = '1e9f6460c977'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('short_name', sa.String(length=8), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('station', 'short_name')
    ### end Alembic commands ###
