"""LogEntries

Revision ID: 2320f7c46bd4
Revises: 1eb3f00520c
Create Date: 2013-08-12 14:06:34.301000

"""

# revision identifiers, used by Alembic.
revision = '2320f7c46bd4'
down_revision = '1eb3f00520c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('reception_timestamp', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_entry')
    ### end Alembic commands ###
