"""Station Update for e-mails

Revision ID: 2450ae9222bd
Revises: 4d3fe3d7bdfd
Create Date: 2015-05-30 14:19:54.513386

"""

# revision identifiers, used by Alembic.
revision = '2450ae9222bd'
down_revision = '4d3fe3d7bdfd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('email_address', sa.String(length=255), nullable=True))
    op.add_column('station', sa.Column('email_description', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('station', 'email_description')
    op.drop_column('station', 'email_address')
    ### end Alembic commands ###
