"""LogEntries

Revision ID: 2683aba1ae0a
Revises: 4400d67e4640
Create Date: 2013-08-12 14:09:07.368000

"""

# revision identifiers, used by Alembic.
revision = '2683aba1ae0a'
down_revision = '4400d67e4640'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_entry', sa.Column('reception_timestamp', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_entry', 'reception_timestamp')
    ### end Alembic commands ###
