"""Public Prefix for VIS Image

Revision ID: 30a24ab759f9
Revises: 39df91a7b160
Create Date: 2014-12-04 17:21:32.939098

"""

# revision identifiers, used by Alembic.
revision = '30a24ab759f9'
down_revision = '39df91a7b160'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('image_url_prefix', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('picture', 'image_url_prefix')
    ### end Alembic commands ###
