"""Chanel2Station

Revision ID: 314a9041017e
Revises: 3911cebb4b90
Create Date: 2014-06-03 14:58:06.515094

"""

# revision identifiers, used by Alembic.
revision = '314a9041017e'
down_revision = '3911cebb4b90'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', u'epg_picture_id')
    op.add_column('station', sa.Column('epg_picture_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('station', 'epg_picture_id')
    op.add_column('channel', sa.Column(u'epg_picture_id', mysql.INTEGER(display_width=11), nullable=True))
    ### end Alembic commands ###
