"""Added PictureForEPG

Revision ID: 33741d7ea890
Revises: 1f5a646334e1
Create Date: 2014-06-03 14:15:11.108045

"""

# revision identifiers, used by Alembic.
revision = '33741d7ea890'
down_revision = '1f5a646334e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picture_forEPG',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orga', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picture_forEPG')
    ### end Alembic commands ###
