"""Added default picture

Revision ID: 33c72a47d6bb
Revises: 1e1119ba9a4
Create Date: 2013-08-06 15:56:50.300000

"""

# revision identifiers, used by Alembic.
revision = '33c72a47d6bb'
down_revision = '1e1119ba9a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('default_picture_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'default_picture_id')
    ### end Alembic commands ###
