"""Added schedule

Revision ID: 37924d95f098
Revises: 41808ec16aa1
Create Date: 2013-08-19 16:21:48.293000

"""

# revision identifiers, used by Alembic.
revision = '37924d95f098'
down_revision = '41808ec16aa1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('start_hour', sa.Integer(), nullable=True),
    sa.Column('start_minute', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    ### end Alembic commands ###
