"""Added EPG-LogoImage link

Revision ID: 39df91a7b160
Revises: 423350744c8c
Create Date: 2014-12-04 16:51:33.978089

"""

# revision identifiers, used by Alembic.
revision = '39df91a7b160'
down_revision = '423350744c8c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('default_logo_image_id', sa.Integer(), nullable=True))
    op.drop_column('station', 'epg_picture_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('epg_picture_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('station', 'default_logo_image_id')
    ### end Alembic commands ###
