"""Add stream and mimtype to channels for ip

Revision ID: 3e4640ec7bef
Revises: 528cfcb91ede
Create Date: 2015-05-30 17:05:21.357765

"""

# revision identifiers, used by Alembic.
revision = '3e4640ec7bef'
down_revision = '528cfcb91ede'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('mime_type', sa.String(length=64), nullable=True))
    op.add_column('channel', sa.Column('stream_url', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'stream_url')
    op.drop_column('channel', 'mime_type')
    ### end Alembic commands ###
