"""Added service following tables

Revision ID: 4121a98095b5
Revises: 37924d95f098
Create Date: 2013-08-23 09:00:32.793000

"""

# revision identifiers, used by Alembic.
revision = '4121a98095b5'
down_revision = '37924d95f098'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generic_service_following_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('offset', sa.Integer(), nullable=True),
    sa.Column('mine_type', sa.String(length=255), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('channel_uri', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generic_service_following_entry')
    ### end Alembic commands ###
