"""Added Services to Station Model

Revision ID: 423350744c8c
Revises: 519654f4eb9c
Create Date: 2014-12-04 11:28:14.972747

"""

# revision identifiers, used by Alembic.
revision = '423350744c8c'
down_revision = '519654f4eb9c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('radioepg_enabled', sa.Boolean(), nullable=True))
    op.add_column('station', sa.Column('radioepg_service', sa.String(length=255), nullable=True))
    op.add_column('station', sa.Column('radiotag_enabled', sa.Boolean(), nullable=True))
    op.add_column('station', sa.Column('radiotag_service', sa.String(length=255), nullable=True))
    op.add_column('station', sa.Column('radiovis_enabled', sa.Boolean(), nullable=True))
    op.add_column('station', sa.Column('radiovis_service', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('station', 'radiovis_service')
    op.drop_column('station', 'radiovis_enabled')
    op.drop_column('station', 'radiotag_service')
    op.drop_column('station', 'radiotag_enabled')
    op.drop_column('station', 'radioepg_service')
    op.drop_column('station', 'radioepg_enabled')
    ### end Alembic commands ###
