"""Added show

Revision ID: 485001e8d1b3
Revises: 2683aba1ae0a
Create Date: 2013-08-19 13:56:50.466000

"""

# revision identifiers, used by Alembic.
revision = '485001e8d1b3'
down_revision = '2683aba1ae0a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orga', sa.Integer(), nullable=True),
    sa.Column('medium_name', sa.String(length=255), nullable=True),
    sa.Column('long_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show')
    ### end Alembic commands ###
