"""Added Service Provider

Revision ID: 4891307e6a8c
Revises: e4619239aac
Create Date: 2014-11-21 17:33:21.610477

"""

# revision identifiers, used by Alembic.
revision = '4891307e6a8c'
down_revision = 'e4619239aac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codops', sa.String(length=255), nullable=True),
    sa.Column('short_name', sa.String(length=8), nullable=True),
    sa.Column('medium_name', sa.String(length=16), nullable=True),
    sa.Column('long_name', sa.String(length=128), nullable=True),
    sa.Column('short_description', sa.String(length=180), nullable=True),
    sa.Column('long_description', sa.String(length=1200), nullable=True),
    sa.Column('url_default', sa.String(length=255), nullable=True),
    sa.Column('default_language', sa.String(length=5), nullable=True),
    sa.Column('location_country', sa.String(length=5), nullable=True),
    sa.Column('default_logo_image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['default_logo_image_id'], ['logo_image.id'], name='fk_default_logo_id', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logo_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orga', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('url32x32', sa.String(length=255), nullable=True),
    sa.Column('url112x32', sa.String(length=255), nullable=True),
    sa.Column('url128x128', sa.String(length=255), nullable=True),
    sa.Column('url320x240', sa.String(length=255), nullable=True),
    sa.Column('url600x600', sa.String(length=255), nullable=True),
    sa.Column('service_provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_provider_id'], ['service_provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'station', sa.Column('service_provider_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'station', 'service_provider_id')
    op.drop_table('logo_image')
    op.drop_table('service_provider')
    ### end Alembic commands ###
