"""LogEntries

Revision ID: 4c03607d9774
Revises: 2320f7c46bd4
Create Date: 2013-08-12 14:07:55.192000

"""

# revision identifiers, used by Alembic.
revision = '4c03607d9774'
down_revision = '2320f7c46bd4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
