"""Added multiple indexes

Revision ID: 4e2dde2d15e6
Revises: 3e4640ec7bef
Create Date: 2015-06-01 20:55:32.714080

"""

# revision identifiers, used by Alembic.
revision = '4e2dde2d15e6'
down_revision = '3e4640ec7bef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_channel_type_id'), 'channel', ['type_id'], unique=False)
    op.create_index(op.f('ix_ecc_iso'), 'ecc', ['iso'], unique=False)
    op.create_index(op.f('ix_service_provider_codops'), 'service_provider', ['codops'], unique=False)
    op.create_index(op.f('ix_station_orga'), 'station', ['orga'], unique=False)
    op.create_index(op.f('ix_station_radioepg_enabled'), 'station', ['radioepg_enabled'], unique=False)
    op.create_index(op.f('ix_station_radiotag_enabled'), 'station', ['radiotag_enabled'], unique=False)
    op.create_index(op.f('ix_station_radiovis_enabled'), 'station', ['radiovis_enabled'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_station_radiovis_enabled'), table_name='station')
    op.drop_index(op.f('ix_station_radiotag_enabled'), table_name='station')
    op.drop_index(op.f('ix_station_radioepg_enabled'), table_name='station')
    op.drop_index(op.f('ix_station_orga'), table_name='station')
    op.drop_index(op.f('ix_service_provider_codops'), table_name='service_provider')
    op.drop_index(op.f('ix_ecc_iso'), table_name='ecc')
    op.drop_index(op.f('ix_channel_type_id'), table_name='channel')
    ### end Alembic commands ###
