"""Added stations

Revision ID: 4e86d9f6bec9
Revises: None
Create Date: 2013-08-05 15:12:58.511000

"""

# revision identifiers, used by Alembic.
revision = '4e86d9f6bec9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orga', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('station')
    ### end Alembic commands ###
