"""Added fields to LogoImage

Revision ID: 519654f4eb9c
Revises: 4891307e6a8c
Create Date: 2014-11-28 10:35:10.677936

"""

# revision identifiers, used by Alembic.
revision = '519654f4eb9c'
down_revision = '4891307e6a8c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logo_image', sa.Column('codops', sa.String(length=255), nullable=True))
    op.add_column('logo_image', sa.Column('name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logo_image', 'name')
    op.drop_column('logo_image', 'codops')
    ### end Alembic commands ###
