"""Add bitrate to channels for ip

Revision ID: 528cfcb91ede
Revises: 2450ae9222bd
Create Date: 2015-05-30 16:48:05.159741

"""

# revision identifiers, used by Alembic.
revision = '528cfcb91ede'
down_revision = '2450ae9222bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('bitrate', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'bitrate')
    ### end Alembic commands ###
