"""Added double indexes

Revision ID: 5783809706d2
Revises: 4e2dde2d15e6
Create Date: 2015-06-01 21:08:15.106408

"""

# revision identifiers, used by Alembic.
revision = '5783809706d2'
down_revision = '4e2dde2d15e6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ecc_pi_ecc', 'ecc', ['pi', 'ecc'], unique=False)
    op.create_index('ix_station_spid_radioepg_enabled', 'station', ['service_provider_id', 'radioepg_enabled'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_station_spid_radioepg_enabled', table_name='station')
    op.drop_index('ix_ecc_pi_ecc', table_name='ecc')
    ### end Alembic commands ###
