"""Added channels

Revision ID: 79cf16aef0b
Revises: 4e86d9f6bec9
Create Date: 2013-08-05 17:00:59.864000

"""

# revision identifiers, used by Alembic.
revision = '79cf16aef0b'
down_revision = '4e86d9f6bec9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel')
    ### end Alembic commands ###
