"""Added channel client's foreign key.

Revision ID: b4009d2ab0ba
Revises: 7045978e05ec
Create Date: 2018-10-22 12:59:51.188560

"""

# revision identifiers, used by Alembic.
revision = 'b4009d2ab0ba'
down_revision = '7045978e05ec'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('fk_client', sa.Integer(), nullable=True))
    op.create_foreign_key('channel_clients_id_fk', 'channel', 'clients', ['fk_client'], ['id'], use_alter=True, ondelete=u'CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('channel_clients_id_fk', 'channel', type_='foreignkey')
    op.drop_column('channel', 'fk_client')
    # ### end Alembic commands ###
