# Generated by Django 3.0.6 on 2020-05-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("length", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medium_name", models.CharField(max_length=255)),
                ("long_name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("color", models.CharField(max_length=7)),
                ("schedules", models.ManyToManyField(to="shows.Schedule")),
            ],
        ),
    ]
